# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [4]:
import pandas as pd
url= "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df=pd.read_csv(url)

In [7]:
print(df.head())

   Unnamed: 0 Customer       State  Customer Lifetime Value Response  \
0           0  DK49336     Arizona              4809.216960       No
1           1  KX64629  California              2228.525238       No
2           2  LZ68649  Washington             14947.917300       No
3           3  XL78013      Oregon             22332.439460      Yes
4           4  QA50777      Oregon              9025.067525       No

   Coverage Education Effective To Date EmploymentStatus Gender  ...  \
0     Basic   College           2/18/11         Employed      M  ...
1     Basic   College           1/18/11       Unemployed      F  ...
2     Basic  Bachelor           2/10/11         Employed      M  ...
3  Extended   College           1/11/11         Employed      M  ...
4   Premium  Bachelor           1/17/11    Medical Leave      F  ...

   Number of Open Complaints Number of Policies     Policy Type        Policy  \
0                        0.0                  9  Corporate Auto  Corporate L3
1                        0.0                  1   Personal Auto   Personal L3
2                        0.0                  2   Personal Auto   Personal L3
3                        0.0                  2  Corporate Auto  Corporate L3
4                        NaN                  7   Personal Auto   Personal L2

   Renew Offer Type  Sales Channel  Total Claim Amount  Vehicle Class  \
0            Offer3          Agent          292.800000  Four-Door Car
1            Offer4    Call Center          744.924331  Four-Door Car
2            Offer3    Call Center          480.000000            SUV
3            Offer2         Branch          484.013411  Four-Door Car
4            Offer1         Branch          707.925645  Four-Door Car

  Vehicle Size Vehicle Type
0      Medsize          NaN
1      Medsize          NaN
2      Medsize            A
3      Medsize            A
4      Medsize          NaN

[5 rows x 26 columns]

In [8]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [9]:
df.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type'],
      dtype='object')

In [10]:
low_claim_yes_response = df[
    (df["total_claim_amount"] < 1000) &
    (df["response"] == "Yes")
]

low_claim_yes_response

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [11]:
yes_customers = df[df["response"] == "Yes"]

profitability_summary = yes_customers.groupby(["policy_type", "gender"]).agg(
    avg_monthly_premium=("monthly_premium_auto", "mean"),
    avg_customer_lifetime_value=("customer_lifetime_value", "mean"),
    avg_total_claim_amount=("total_claim_amount", "mean"),
    customer_count=("response", "count")
).round(2)

profitability_summary["clv_to_claim_ratio"] = (
    profitability_summary["avg_customer_lifetime_value"] /
    profitability_summary["avg_total_claim_amount"]
).round(2)

profitability_summary = profitability_summary.sort_values(
    by="clv_to_claim_ratio",
    ascending=False
)

profitability_summary

,,avg_monthly_premium,avg_customer_lifetime_value,avg_total_claim_amount,customer_count,clv_to_claim_ratio
policy_type,gender,,,,,
Corporate Auto,M,92.19,7944.47,408.58,154,19.44
Special Auto,M,86.34,8247.09,429.53,32,19.20
Personal Auto,F,99.00,8339.79,452.97,540,18.41
Corporate Auto,F,94.30,7712.63,433.74,169,17.78
Special Auto,F,92.31,7691.58,453.28,35,16.97
Personal Auto,M,91.09,7448.38,457.01,536,16.30

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [12]:
states_over_500 = (
    df["state"]
    .value_counts()
    .reset_index()
)

states_over_500.columns = ["state", "customer_count"]

states_over_500 = states_over_500[states_over_500["customer_count"] > 500]

states_over_500

        state  customer_count
0  California            3552
1      Oregon            2909
2     Arizona            1937
3      Nevada             993
4  Washington             888

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [13]:
clv_by_education_gender = df.groupby(["education", "gender"]).agg(
    max_customer_lifetime_value=("customer_lifetime_value", "max"),
    min_customer_lifetime_value=("customer_lifetime_value", "min"),
    median_customer_lifetime_value=("customer_lifetime_value", "median")
).round(2)

clv_by_education_gender = clv_by_education_gender.sort_values(
    by="median_customer_lifetime_value",
    ascending=False
)

display(clv_by_education_gender)

                             max_customer_lifetime_value  \
education            gender
High School or Below M                          83325.38
                     F                          55277.45
College              M                          61134.68
Master               F                          51016.07
Bachelor             F                          73225.96
College              F                          61850.19
Master               M                          50568.26
Doctor               M                          32677.34
Bachelor             M                          67907.27
Doctor               F                          44856.11

                             min_customer_lifetime_value  \
education            gender
High School or Below M                           1940.98
                     F                           2144.92
College              M                           1918.12
Master               F                           2417.78
Bachelor             F                           1904.00
College              F                           1898.68
Master               M                           2272.31
Doctor               M                           2267.60
Bachelor             M                           1898.01
Doctor               F                           2395.57

                             median_customer_lifetime_value
education            gender
High School or Below M                              6286.73
                     F                              6039.55
College              M                              6005.85
Master               F                              5729.86
Bachelor             F                              5640.51
College              F                              5623.61
Master               M                              5579.10
Doctor               M                              5577.67
Bachelor             M                              5548.03
Doctor               F                              5332.46

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here